name: "Tag & Deploy Action"

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16.8

      - name: Install
        run: yarn ci

      - name: Run Tests
        run: yarn test

      - name: Update v1 Tag
        uses: hole19/git-tag-action@master
        env:
          TAG: v1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
